singleuser:
  image:
    name: jupyter/minimal-notebook
    tag: latest
  defaultUrl: /lab
  memory:
    guarantee: 100M
  profileList:
    - display_name: "Minimal environment"
      description: "Simple jupyter environment"
      default: true
    - display_name: "Spark environment"
      description: "The Jupyter Stacks spark image!"
      kubespawner_override:
        image: jupyter/pyspark-notebook
        tag: latest
        cmd: ["/usr/local/bin/start.sh", "jupyterhub-singleuser"]
proxy:
  secretToken: 'ab4c397148c38b4ebe8813480f785633ea945065ecd787a2caa1d73bf9058daf'
  service:
    type: ClusterIP
hub:
  config:
    Authenticator:
      admin_users:
        - admin
      allowed_users:
        - user
    DummyAuthenticator:
      password: password
    JupyterHub:
      authenticator_class: dummy